# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bolla/C++/ProgCG

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bolla/C++/ProgCG

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bolla/C++/ProgCG/CMakeFiles /home/bolla/C++/ProgCG//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bolla/C++/ProgCG/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ProgCG

# Build rule for target.
ProgCG: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ProgCG
.PHONY : ProgCG

# fast build rule for target.
ProgCG/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/build
.PHONY : ProgCG/fast

includes/BoundingBox.o: includes/BoundingBox.cpp.o
.PHONY : includes/BoundingBox.o

# target to build an object file
includes/BoundingBox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/BoundingBox.cpp.o
.PHONY : includes/BoundingBox.cpp.o

includes/BoundingBox.i: includes/BoundingBox.cpp.i
.PHONY : includes/BoundingBox.i

# target to preprocess a source file
includes/BoundingBox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/BoundingBox.cpp.i
.PHONY : includes/BoundingBox.cpp.i

includes/BoundingBox.s: includes/BoundingBox.cpp.s
.PHONY : includes/BoundingBox.s

# target to generate assembly for a file
includes/BoundingBox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/BoundingBox.cpp.s
.PHONY : includes/BoundingBox.cpp.s

includes/Camera.o: includes/Camera.cpp.o
.PHONY : includes/Camera.o

# target to build an object file
includes/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Camera.cpp.o
.PHONY : includes/Camera.cpp.o

includes/Camera.i: includes/Camera.cpp.i
.PHONY : includes/Camera.i

# target to preprocess a source file
includes/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Camera.cpp.i
.PHONY : includes/Camera.cpp.i

includes/Camera.s: includes/Camera.cpp.s
.PHONY : includes/Camera.s

# target to generate assembly for a file
includes/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Camera.cpp.s
.PHONY : includes/Camera.cpp.s

includes/Carosello.o: includes/Carosello.cpp.o
.PHONY : includes/Carosello.o

# target to build an object file
includes/Carosello.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Carosello.cpp.o
.PHONY : includes/Carosello.cpp.o

includes/Carosello.i: includes/Carosello.cpp.i
.PHONY : includes/Carosello.i

# target to preprocess a source file
includes/Carosello.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Carosello.cpp.i
.PHONY : includes/Carosello.cpp.i

includes/Carosello.s: includes/Carosello.cpp.s
.PHONY : includes/Carosello.s

# target to generate assembly for a file
includes/Carosello.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Carosello.cpp.s
.PHONY : includes/Carosello.cpp.s

includes/Color.o: includes/Color.cpp.o
.PHONY : includes/Color.o

# target to build an object file
includes/Color.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Color.cpp.o
.PHONY : includes/Color.cpp.o

includes/Color.i: includes/Color.cpp.i
.PHONY : includes/Color.i

# target to preprocess a source file
includes/Color.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Color.cpp.i
.PHONY : includes/Color.cpp.i

includes/Color.s: includes/Color.cpp.s
.PHONY : includes/Color.s

# target to generate assembly for a file
includes/Color.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Color.cpp.s
.PHONY : includes/Color.cpp.s

includes/FrameBuffer.o: includes/FrameBuffer.cpp.o
.PHONY : includes/FrameBuffer.o

# target to build an object file
includes/FrameBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/FrameBuffer.cpp.o
.PHONY : includes/FrameBuffer.cpp.o

includes/FrameBuffer.i: includes/FrameBuffer.cpp.i
.PHONY : includes/FrameBuffer.i

# target to preprocess a source file
includes/FrameBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/FrameBuffer.cpp.i
.PHONY : includes/FrameBuffer.cpp.i

includes/FrameBuffer.s: includes/FrameBuffer.cpp.s
.PHONY : includes/FrameBuffer.s

# target to generate assembly for a file
includes/FrameBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/FrameBuffer.cpp.s
.PHONY : includes/FrameBuffer.cpp.s

includes/Input.o: includes/Input.cpp.o
.PHONY : includes/Input.o

# target to build an object file
includes/Input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Input.cpp.o
.PHONY : includes/Input.cpp.o

includes/Input.i: includes/Input.cpp.i
.PHONY : includes/Input.i

# target to preprocess a source file
includes/Input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Input.cpp.i
.PHONY : includes/Input.cpp.i

includes/Input.s: includes/Input.cpp.s
.PHONY : includes/Input.s

# target to generate assembly for a file
includes/Input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Input.cpp.s
.PHONY : includes/Input.cpp.s

includes/Intersection.o: includes/Intersection.cpp.o
.PHONY : includes/Intersection.o

# target to build an object file
includes/Intersection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Intersection.cpp.o
.PHONY : includes/Intersection.cpp.o

includes/Intersection.i: includes/Intersection.cpp.i
.PHONY : includes/Intersection.i

# target to preprocess a source file
includes/Intersection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Intersection.cpp.i
.PHONY : includes/Intersection.cpp.i

includes/Intersection.s: includes/Intersection.cpp.s
.PHONY : includes/Intersection.s

# target to generate assembly for a file
includes/Intersection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Intersection.cpp.s
.PHONY : includes/Intersection.cpp.s

includes/Ligth.o: includes/Ligth.cpp.o
.PHONY : includes/Ligth.o

# target to build an object file
includes/Ligth.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Ligth.cpp.o
.PHONY : includes/Ligth.cpp.o

includes/Ligth.i: includes/Ligth.cpp.i
.PHONY : includes/Ligth.i

# target to preprocess a source file
includes/Ligth.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Ligth.cpp.i
.PHONY : includes/Ligth.cpp.i

includes/Ligth.s: includes/Ligth.cpp.s
.PHONY : includes/Ligth.s

# target to generate assembly for a file
includes/Ligth.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Ligth.cpp.s
.PHONY : includes/Ligth.cpp.s

includes/Mesh.o: includes/Mesh.cpp.o
.PHONY : includes/Mesh.o

# target to build an object file
includes/Mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Mesh.cpp.o
.PHONY : includes/Mesh.cpp.o

includes/Mesh.i: includes/Mesh.cpp.i
.PHONY : includes/Mesh.i

# target to preprocess a source file
includes/Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Mesh.cpp.i
.PHONY : includes/Mesh.cpp.i

includes/Mesh.s: includes/Mesh.cpp.s
.PHONY : includes/Mesh.s

# target to generate assembly for a file
includes/Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Mesh.cpp.s
.PHONY : includes/Mesh.cpp.s

includes/ModelLoader.o: includes/ModelLoader.cpp.o
.PHONY : includes/ModelLoader.o

# target to build an object file
includes/ModelLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/ModelLoader.cpp.o
.PHONY : includes/ModelLoader.cpp.o

includes/ModelLoader.i: includes/ModelLoader.cpp.i
.PHONY : includes/ModelLoader.i

# target to preprocess a source file
includes/ModelLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/ModelLoader.cpp.i
.PHONY : includes/ModelLoader.cpp.i

includes/ModelLoader.s: includes/ModelLoader.cpp.s
.PHONY : includes/ModelLoader.s

# target to generate assembly for a file
includes/ModelLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/ModelLoader.cpp.s
.PHONY : includes/ModelLoader.cpp.s

includes/Orbit.o: includes/Orbit.cpp.o
.PHONY : includes/Orbit.o

# target to build an object file
includes/Orbit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Orbit.cpp.o
.PHONY : includes/Orbit.cpp.o

includes/Orbit.i: includes/Orbit.cpp.i
.PHONY : includes/Orbit.i

# target to preprocess a source file
includes/Orbit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Orbit.cpp.i
.PHONY : includes/Orbit.cpp.i

includes/Orbit.s: includes/Orbit.cpp.s
.PHONY : includes/Orbit.s

# target to generate assembly for a file
includes/Orbit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Orbit.cpp.s
.PHONY : includes/Orbit.cpp.s

includes/Renderable.o: includes/Renderable.cpp.o
.PHONY : includes/Renderable.o

# target to build an object file
includes/Renderable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Renderable.cpp.o
.PHONY : includes/Renderable.cpp.o

includes/Renderable.i: includes/Renderable.cpp.i
.PHONY : includes/Renderable.i

# target to preprocess a source file
includes/Renderable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Renderable.cpp.i
.PHONY : includes/Renderable.cpp.i

includes/Renderable.s: includes/Renderable.cpp.s
.PHONY : includes/Renderable.s

# target to generate assembly for a file
includes/Renderable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Renderable.cpp.s
.PHONY : includes/Renderable.cpp.s

includes/Scene.o: includes/Scene.cpp.o
.PHONY : includes/Scene.o

# target to build an object file
includes/Scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Scene.cpp.o
.PHONY : includes/Scene.cpp.o

includes/Scene.i: includes/Scene.cpp.i
.PHONY : includes/Scene.i

# target to preprocess a source file
includes/Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Scene.cpp.i
.PHONY : includes/Scene.cpp.i

includes/Scene.s: includes/Scene.cpp.s
.PHONY : includes/Scene.s

# target to generate assembly for a file
includes/Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Scene.cpp.s
.PHONY : includes/Scene.cpp.s

includes/Shader.o: includes/Shader.cpp.o
.PHONY : includes/Shader.o

# target to build an object file
includes/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Shader.cpp.o
.PHONY : includes/Shader.cpp.o

includes/Shader.i: includes/Shader.cpp.i
.PHONY : includes/Shader.i

# target to preprocess a source file
includes/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Shader.cpp.i
.PHONY : includes/Shader.cpp.i

includes/Shader.s: includes/Shader.cpp.s
.PHONY : includes/Shader.s

# target to generate assembly for a file
includes/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Shader.cpp.s
.PHONY : includes/Shader.cpp.s

includes/Terrain.o: includes/Terrain.cpp.o
.PHONY : includes/Terrain.o

# target to build an object file
includes/Terrain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Terrain.cpp.o
.PHONY : includes/Terrain.cpp.o

includes/Terrain.i: includes/Terrain.cpp.i
.PHONY : includes/Terrain.i

# target to preprocess a source file
includes/Terrain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Terrain.cpp.i
.PHONY : includes/Terrain.cpp.i

includes/Terrain.s: includes/Terrain.cpp.s
.PHONY : includes/Terrain.s

# target to generate assembly for a file
includes/Terrain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Terrain.cpp.s
.PHONY : includes/Terrain.cpp.s

includes/Texture.o: includes/Texture.cpp.o
.PHONY : includes/Texture.o

# target to build an object file
includes/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Texture.cpp.o
.PHONY : includes/Texture.cpp.o

includes/Texture.i: includes/Texture.cpp.i
.PHONY : includes/Texture.i

# target to preprocess a source file
includes/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Texture.cpp.i
.PHONY : includes/Texture.cpp.i

includes/Texture.s: includes/Texture.cpp.s
.PHONY : includes/Texture.s

# target to generate assembly for a file
includes/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Texture.cpp.s
.PHONY : includes/Texture.cpp.s

includes/Track.o: includes/Track.cpp.o
.PHONY : includes/Track.o

# target to build an object file
includes/Track.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Track.cpp.o
.PHONY : includes/Track.cpp.o

includes/Track.i: includes/Track.cpp.i
.PHONY : includes/Track.i

# target to preprocess a source file
includes/Track.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Track.cpp.i
.PHONY : includes/Track.cpp.i

includes/Track.s: includes/Track.cpp.s
.PHONY : includes/Track.s

# target to generate assembly for a file
includes/Track.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Track.cpp.s
.PHONY : includes/Track.cpp.s

includes/Trackball.o: includes/Trackball.cpp.o
.PHONY : includes/Trackball.o

# target to build an object file
includes/Trackball.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Trackball.cpp.o
.PHONY : includes/Trackball.cpp.o

includes/Trackball.i: includes/Trackball.cpp.i
.PHONY : includes/Trackball.i

# target to preprocess a source file
includes/Trackball.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Trackball.cpp.i
.PHONY : includes/Trackball.cpp.i

includes/Trackball.s: includes/Trackball.cpp.s
.PHONY : includes/Trackball.s

# target to generate assembly for a file
includes/Trackball.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/Trackball.cpp.s
.PHONY : includes/Trackball.cpp.s

includes/materials/LitMaterial.o: includes/materials/LitMaterial.cpp.o
.PHONY : includes/materials/LitMaterial.o

# target to build an object file
includes/materials/LitMaterial.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/materials/LitMaterial.cpp.o
.PHONY : includes/materials/LitMaterial.cpp.o

includes/materials/LitMaterial.i: includes/materials/LitMaterial.cpp.i
.PHONY : includes/materials/LitMaterial.i

# target to preprocess a source file
includes/materials/LitMaterial.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/materials/LitMaterial.cpp.i
.PHONY : includes/materials/LitMaterial.cpp.i

includes/materials/LitMaterial.s: includes/materials/LitMaterial.cpp.s
.PHONY : includes/materials/LitMaterial.s

# target to generate assembly for a file
includes/materials/LitMaterial.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/materials/LitMaterial.cpp.s
.PHONY : includes/materials/LitMaterial.cpp.s

includes/materials/Material.o: includes/materials/Material.cpp.o
.PHONY : includes/materials/Material.o

# target to build an object file
includes/materials/Material.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/materials/Material.cpp.o
.PHONY : includes/materials/Material.cpp.o

includes/materials/Material.i: includes/materials/Material.cpp.i
.PHONY : includes/materials/Material.i

# target to preprocess a source file
includes/materials/Material.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/materials/Material.cpp.i
.PHONY : includes/materials/Material.cpp.i

includes/materials/Material.s: includes/materials/Material.cpp.s
.PHONY : includes/materials/Material.s

# target to generate assembly for a file
includes/materials/Material.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/materials/Material.cpp.s
.PHONY : includes/materials/Material.cpp.s

includes/materials/TerrainMaterial.o: includes/materials/TerrainMaterial.cpp.o
.PHONY : includes/materials/TerrainMaterial.o

# target to build an object file
includes/materials/TerrainMaterial.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/materials/TerrainMaterial.cpp.o
.PHONY : includes/materials/TerrainMaterial.cpp.o

includes/materials/TerrainMaterial.i: includes/materials/TerrainMaterial.cpp.i
.PHONY : includes/materials/TerrainMaterial.i

# target to preprocess a source file
includes/materials/TerrainMaterial.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/materials/TerrainMaterial.cpp.i
.PHONY : includes/materials/TerrainMaterial.cpp.i

includes/materials/TerrainMaterial.s: includes/materials/TerrainMaterial.cpp.s
.PHONY : includes/materials/TerrainMaterial.s

# target to generate assembly for a file
includes/materials/TerrainMaterial.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/materials/TerrainMaterial.cpp.s
.PHONY : includes/materials/TerrainMaterial.cpp.s

includes/materials/UnlitMaterial.o: includes/materials/UnlitMaterial.cpp.o
.PHONY : includes/materials/UnlitMaterial.o

# target to build an object file
includes/materials/UnlitMaterial.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/materials/UnlitMaterial.cpp.o
.PHONY : includes/materials/UnlitMaterial.cpp.o

includes/materials/UnlitMaterial.i: includes/materials/UnlitMaterial.cpp.i
.PHONY : includes/materials/UnlitMaterial.i

# target to preprocess a source file
includes/materials/UnlitMaterial.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/materials/UnlitMaterial.cpp.i
.PHONY : includes/materials/UnlitMaterial.cpp.i

includes/materials/UnlitMaterial.s: includes/materials/UnlitMaterial.cpp.s
.PHONY : includes/materials/UnlitMaterial.s

# target to generate assembly for a file
includes/materials/UnlitMaterial.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/includes/materials/UnlitMaterial.cpp.s
.PHONY : includes/materials/UnlitMaterial.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/main.cpp.s
.PHONY : main.cpp.s

vendor/imgui/backends/imgui_impl_glfw.o: vendor/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : vendor/imgui/backends/imgui_impl_glfw.o

# target to build an object file
vendor/imgui/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/vendor/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : vendor/imgui/backends/imgui_impl_glfw.cpp.o

vendor/imgui/backends/imgui_impl_glfw.i: vendor/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : vendor/imgui/backends/imgui_impl_glfw.i

# target to preprocess a source file
vendor/imgui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/vendor/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : vendor/imgui/backends/imgui_impl_glfw.cpp.i

vendor/imgui/backends/imgui_impl_glfw.s: vendor/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : vendor/imgui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
vendor/imgui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/vendor/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : vendor/imgui/backends/imgui_impl_glfw.cpp.s

vendor/imgui/backends/imgui_impl_opengl3.o: vendor/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : vendor/imgui/backends/imgui_impl_opengl3.o

# target to build an object file
vendor/imgui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/vendor/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : vendor/imgui/backends/imgui_impl_opengl3.cpp.o

vendor/imgui/backends/imgui_impl_opengl3.i: vendor/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : vendor/imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
vendor/imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/vendor/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : vendor/imgui/backends/imgui_impl_opengl3.cpp.i

vendor/imgui/backends/imgui_impl_opengl3.s: vendor/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : vendor/imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
vendor/imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/vendor/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : vendor/imgui/backends/imgui_impl_opengl3.cpp.s

vendor/imgui/imgui.o: vendor/imgui/imgui.cpp.o
.PHONY : vendor/imgui/imgui.o

# target to build an object file
vendor/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/vendor/imgui/imgui.cpp.o
.PHONY : vendor/imgui/imgui.cpp.o

vendor/imgui/imgui.i: vendor/imgui/imgui.cpp.i
.PHONY : vendor/imgui/imgui.i

# target to preprocess a source file
vendor/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/vendor/imgui/imgui.cpp.i
.PHONY : vendor/imgui/imgui.cpp.i

vendor/imgui/imgui.s: vendor/imgui/imgui.cpp.s
.PHONY : vendor/imgui/imgui.s

# target to generate assembly for a file
vendor/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/vendor/imgui/imgui.cpp.s
.PHONY : vendor/imgui/imgui.cpp.s

vendor/imgui/imgui_draw.o: vendor/imgui/imgui_draw.cpp.o
.PHONY : vendor/imgui/imgui_draw.o

# target to build an object file
vendor/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/vendor/imgui/imgui_draw.cpp.o
.PHONY : vendor/imgui/imgui_draw.cpp.o

vendor/imgui/imgui_draw.i: vendor/imgui/imgui_draw.cpp.i
.PHONY : vendor/imgui/imgui_draw.i

# target to preprocess a source file
vendor/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/vendor/imgui/imgui_draw.cpp.i
.PHONY : vendor/imgui/imgui_draw.cpp.i

vendor/imgui/imgui_draw.s: vendor/imgui/imgui_draw.cpp.s
.PHONY : vendor/imgui/imgui_draw.s

# target to generate assembly for a file
vendor/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/vendor/imgui/imgui_draw.cpp.s
.PHONY : vendor/imgui/imgui_draw.cpp.s

vendor/imgui/imgui_tables.o: vendor/imgui/imgui_tables.cpp.o
.PHONY : vendor/imgui/imgui_tables.o

# target to build an object file
vendor/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/vendor/imgui/imgui_tables.cpp.o
.PHONY : vendor/imgui/imgui_tables.cpp.o

vendor/imgui/imgui_tables.i: vendor/imgui/imgui_tables.cpp.i
.PHONY : vendor/imgui/imgui_tables.i

# target to preprocess a source file
vendor/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/vendor/imgui/imgui_tables.cpp.i
.PHONY : vendor/imgui/imgui_tables.cpp.i

vendor/imgui/imgui_tables.s: vendor/imgui/imgui_tables.cpp.s
.PHONY : vendor/imgui/imgui_tables.s

# target to generate assembly for a file
vendor/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/vendor/imgui/imgui_tables.cpp.s
.PHONY : vendor/imgui/imgui_tables.cpp.s

vendor/imgui/imgui_widgets.o: vendor/imgui/imgui_widgets.cpp.o
.PHONY : vendor/imgui/imgui_widgets.o

# target to build an object file
vendor/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/vendor/imgui/imgui_widgets.cpp.o
.PHONY : vendor/imgui/imgui_widgets.cpp.o

vendor/imgui/imgui_widgets.i: vendor/imgui/imgui_widgets.cpp.i
.PHONY : vendor/imgui/imgui_widgets.i

# target to preprocess a source file
vendor/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/vendor/imgui/imgui_widgets.cpp.i
.PHONY : vendor/imgui/imgui_widgets.cpp.i

vendor/imgui/imgui_widgets.s: vendor/imgui/imgui_widgets.cpp.s
.PHONY : vendor/imgui/imgui_widgets.s

# target to generate assembly for a file
vendor/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/vendor/imgui/imgui_widgets.cpp.s
.PHONY : vendor/imgui/imgui_widgets.cpp.s

vendor/imgui/misc/cpp/imgui_stdlib.o: vendor/imgui/misc/cpp/imgui_stdlib.cpp.o
.PHONY : vendor/imgui/misc/cpp/imgui_stdlib.o

# target to build an object file
vendor/imgui/misc/cpp/imgui_stdlib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/vendor/imgui/misc/cpp/imgui_stdlib.cpp.o
.PHONY : vendor/imgui/misc/cpp/imgui_stdlib.cpp.o

vendor/imgui/misc/cpp/imgui_stdlib.i: vendor/imgui/misc/cpp/imgui_stdlib.cpp.i
.PHONY : vendor/imgui/misc/cpp/imgui_stdlib.i

# target to preprocess a source file
vendor/imgui/misc/cpp/imgui_stdlib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/vendor/imgui/misc/cpp/imgui_stdlib.cpp.i
.PHONY : vendor/imgui/misc/cpp/imgui_stdlib.cpp.i

vendor/imgui/misc/cpp/imgui_stdlib.s: vendor/imgui/misc/cpp/imgui_stdlib.cpp.s
.PHONY : vendor/imgui/misc/cpp/imgui_stdlib.s

# target to generate assembly for a file
vendor/imgui/misc/cpp/imgui_stdlib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ProgCG.dir/build.make CMakeFiles/ProgCG.dir/vendor/imgui/misc/cpp/imgui_stdlib.cpp.s
.PHONY : vendor/imgui/misc/cpp/imgui_stdlib.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... ProgCG"
	@echo "... includes/BoundingBox.o"
	@echo "... includes/BoundingBox.i"
	@echo "... includes/BoundingBox.s"
	@echo "... includes/Camera.o"
	@echo "... includes/Camera.i"
	@echo "... includes/Camera.s"
	@echo "... includes/Carosello.o"
	@echo "... includes/Carosello.i"
	@echo "... includes/Carosello.s"
	@echo "... includes/Color.o"
	@echo "... includes/Color.i"
	@echo "... includes/Color.s"
	@echo "... includes/FrameBuffer.o"
	@echo "... includes/FrameBuffer.i"
	@echo "... includes/FrameBuffer.s"
	@echo "... includes/Input.o"
	@echo "... includes/Input.i"
	@echo "... includes/Input.s"
	@echo "... includes/Intersection.o"
	@echo "... includes/Intersection.i"
	@echo "... includes/Intersection.s"
	@echo "... includes/Ligth.o"
	@echo "... includes/Ligth.i"
	@echo "... includes/Ligth.s"
	@echo "... includes/Mesh.o"
	@echo "... includes/Mesh.i"
	@echo "... includes/Mesh.s"
	@echo "... includes/ModelLoader.o"
	@echo "... includes/ModelLoader.i"
	@echo "... includes/ModelLoader.s"
	@echo "... includes/Orbit.o"
	@echo "... includes/Orbit.i"
	@echo "... includes/Orbit.s"
	@echo "... includes/Renderable.o"
	@echo "... includes/Renderable.i"
	@echo "... includes/Renderable.s"
	@echo "... includes/Scene.o"
	@echo "... includes/Scene.i"
	@echo "... includes/Scene.s"
	@echo "... includes/Shader.o"
	@echo "... includes/Shader.i"
	@echo "... includes/Shader.s"
	@echo "... includes/Terrain.o"
	@echo "... includes/Terrain.i"
	@echo "... includes/Terrain.s"
	@echo "... includes/Texture.o"
	@echo "... includes/Texture.i"
	@echo "... includes/Texture.s"
	@echo "... includes/Track.o"
	@echo "... includes/Track.i"
	@echo "... includes/Track.s"
	@echo "... includes/Trackball.o"
	@echo "... includes/Trackball.i"
	@echo "... includes/Trackball.s"
	@echo "... includes/materials/LitMaterial.o"
	@echo "... includes/materials/LitMaterial.i"
	@echo "... includes/materials/LitMaterial.s"
	@echo "... includes/materials/Material.o"
	@echo "... includes/materials/Material.i"
	@echo "... includes/materials/Material.s"
	@echo "... includes/materials/TerrainMaterial.o"
	@echo "... includes/materials/TerrainMaterial.i"
	@echo "... includes/materials/TerrainMaterial.s"
	@echo "... includes/materials/UnlitMaterial.o"
	@echo "... includes/materials/UnlitMaterial.i"
	@echo "... includes/materials/UnlitMaterial.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... vendor/imgui/backends/imgui_impl_glfw.o"
	@echo "... vendor/imgui/backends/imgui_impl_glfw.i"
	@echo "... vendor/imgui/backends/imgui_impl_glfw.s"
	@echo "... vendor/imgui/backends/imgui_impl_opengl3.o"
	@echo "... vendor/imgui/backends/imgui_impl_opengl3.i"
	@echo "... vendor/imgui/backends/imgui_impl_opengl3.s"
	@echo "... vendor/imgui/imgui.o"
	@echo "... vendor/imgui/imgui.i"
	@echo "... vendor/imgui/imgui.s"
	@echo "... vendor/imgui/imgui_draw.o"
	@echo "... vendor/imgui/imgui_draw.i"
	@echo "... vendor/imgui/imgui_draw.s"
	@echo "... vendor/imgui/imgui_tables.o"
	@echo "... vendor/imgui/imgui_tables.i"
	@echo "... vendor/imgui/imgui_tables.s"
	@echo "... vendor/imgui/imgui_widgets.o"
	@echo "... vendor/imgui/imgui_widgets.i"
	@echo "... vendor/imgui/imgui_widgets.s"
	@echo "... vendor/imgui/misc/cpp/imgui_stdlib.o"
	@echo "... vendor/imgui/misc/cpp/imgui_stdlib.i"
	@echo "... vendor/imgui/misc/cpp/imgui_stdlib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

